### ISSUE TITLE
chrome浏览器打印pdf文件资料不全问题

### ISSUE THREAD

**Issue by YuyangHYY** [mcc108/resume#3]
你好 这是我最近仿照你的项目修改的一个简历 - https://yuyanghyy.github.io/cv/
#不过目前遇到个问题，chrome打印pdf生成的pdf文件显示不全，无法进行自动分页。

**Comment by cong-min** [comment]
因为在打印时，这里利用css的 `@media print` 固定了内容的高度为一页。

你可以在 `print.less` 文件内的 [src/css/print.less#L8](https://github.com/mcc108/resume/blob/2103596429e9151f5f4b2e3fd7e4ba27e31d2e29/src/css/print.less#L8) 将 `.content` 的固定高度 `height` 注释掉
```css
.content {
        width: 970px;
        /* height: 1372px; */
        margin: 0 auto;
        border-radius: 0;
...
```

**Comment by YuyangHYY** [comment]
<img width="421" alt="2018-05-30 14 23 03" src="https://user-images.githubusercontent.com/19391002/40702576-005719fe-6415-11e8-9c52-96d298e88d80.png">
奇了怪了，注释掉还是不能打印出第二页

**Comment by cong-min** [comment]
@YuyangHYY  有 `npm run dev` 或者 `npm run build` 嘛？
此外你的 `589` 行也需要注释掉

**Comment by YuyangHYY** [comment]
@mcc108 亲 我按照你说的做了 还是打印不出来全部的
<img width="977" alt="2018-05-31 09 13 37" src="https://user-images.githubusercontent.com/19391002/40755899-0af3876e-64b3-11e8-8eab-a011a2f3e242.png">

**Comment by YuyangHYY** [comment]
@mcc108 解决了 谢谢 不需要注释589
